import { Team } from './teams.component';

export const teamMap: Map<string, Team> = new Map<string, Team>();
teamMap.set('VVHE', {
  name: 'Volleyball Verein Humann Essen',
  logo: '/assets/vvhe_logo.jpg',
  foto: '/assets/vvhe_foto.jpg',
  players: [
    {
      number: 1,
      firstName: 'Jonas',
      lastName: 'Espelage',
      position: 'MB',
      year: 2005,
    },
    {
      number: 2,
      firstName: 'Henry',
      lastName: 'Gerding',
      position: 'AA',
      year: 2006,
    },
    {
      number: 3,
      firstName: 'Luca',
      lastName: 'Grünheit',
      position: 'L',
      year: 2005,
    },
    {
      number: 4,
      firstName: 'Fynn',
      lastName: 'Heymer',
      position: 'AA/L',
      year: 2005,
    },
    {
      number: 5,
      lastName: 'Ignaczak',
      firstName: 'Mika',
      year: 2006,
      position: 'Z',
    },
    {
      number: 6,
      lastName: 'Juditzki',
      firstName: 'Jonah',
      year: 2005,
      position: 'Z',
    },
    {
      number: 7,
      lastName: 'Kott',
      firstName: 'Niklas',
      year: 2005,
      position: 'MB',
    },
    {
      number: 8,
      lastName: 'Köhnen',
      firstName: 'Jakob',
      year: 2005,
      position: 'AA/L',
    },
    {
      number: 9,
      lastName: 'Marijanovic',
      firstName: 'Dejan',
      year: 2006,
      position: 'D',
    },
    {
      number: 10,
      lastName: 'Neuhaus',
      firstName: 'Jakob',
      year: 2005,
      position: 'AA',
    },
    {
      number: 11,
      lastName: 'Prions',
      firstName: 'Moritz',
      year: 2005,
      position: 'D',
    },
    {
      number: 12,
      lastName: 'Strecker',
      firstName: 'Leif',
      year: 2005,
      position: 'MB',
    },
    {
      number: 13,
      lastName: 'Strecker',
      firstName: 'Yul',
      year: 2007,
      position: 'AA/L',
    },
    {
      number: 14,
      lastName: 'Thomzik',
      firstName: 'Piet',
      year: 2005,
      position: 'MB',
    },
    {
      number: 15,
      lastName: 'Müller',
      firstName: 'Milan',
      year: 2005,
      position: 'AA',
    },
  ],
  coaches: [
    {
      lastName: 'Wojtczak',
      firstName: 'Thomas',
      role: 'Trainer*in',
    },
    {
      lastName: 'Mrozek',
      firstName: 'Linus',
      role: 'Betreuer*in',
    },
    {
      firstName: 'Konstantin',
      lastName: 'Brandt',
      role: 'Betreuer*in',
    },
    {
      firstName: 'Till',
      lastName: 'Köhnen',
      role: 'Betreuer*in',
    },
    {
      firstName: 'Lukas',
      lastName: 'Prions',
      role: 'Betreuer*in',
    },
  ],
});

teamMap.set('RSV', {
  name: 'Rhein-Sieg Volleys',
  logo: 'assets/rsv_logo.png',
  foto: 'assets/rsv_foto.jpg',
  players: [
    {
      firstName: 'Moritz',
      lastName: 'Knipp',
      number: 0,
      year: 2005,
      position: 'AA',
    },
    {
      firstName: 'Valentin',
      lastName: 'Mickus',
      number: 0,
      year: 2006,
      position: 'D',
    },
    {
      firstName: 'Julian',
      lastName: 'Sekul',
      number: 0,
      year: 2005,
      position: 'MB',
    },
    {
      firstName: 'Yann',
      lastName: 'Pierre',
      number: 0,
      year: 2006,
      position: 'AA',
    },
    {
      firstName: 'Valentin',
      lastName: 'Drühl',
      number: 0,
      year: 2006,
      position: 'AA',
    },
    {
      firstName: 'Ben',
      lastName: 'Vohwinkel',
      number: 0,
      year: 2005,
      position: 'D',
    },
    {
      firstName: 'Luke',
      lastName: 'Engelke',
      number: 0,
      year: 2006,
      position: 'AA',
    },
    {
      firstName: 'Denys',
      lastName: 'Kurylo',
      number: 0,
      year: 2007,
      position: 'AA',
    },
    {
      firstName: 'Elias',
      lastName: 'Stommel',
      number: 0,
      year: 2005,
      position: 'Z',
    },
    {
      firstName: 'Fynn',
      lastName: 'Bäumer',
      number: 0,
      year: 2005,
      position: 'MB',
    },
    {
      firstName: 'Mohammad',
      lastName: 'Seyed',
      number: 0,
      year: 2006,
      position: 'Z',
    },
    {
      firstName: 'Mathias',
      lastName: 'Klein-Heßling',
      number: 0,
      year: 2006,
      position: 'D',
    },
    {
      firstName: 'Till',
      lastName: 'Spies',
      number: 0,
      year: 2005,
      position: 'L',
    },
    {
      firstName: 'Marko',
      lastName: 'Rakovic',
      number: 0,
      year: 2005,
      position: 'Z',
    },
    {
      firstName: 'Justus',
      lastName: 'von Alvensleben',
      number: 0,
      year: 2005,
      position: 'AA',
    },
    {
      firstName: 'Bjarne',
      lastName: 'Teiwes',
      number: 0,
      year: 2006,
      position: 'MB',
    },
    {
      firstName: 'Arin Qadir',
      lastName: '',
      number: 0,
      year: 2006,
      position: 'Z',
    },
  ],
  coaches: [
    {
      firstName: 'Max',
      lastName: 'Hopf',
      role: 'Trainer*in',
    },
    {
      firstName: 'Jan-Niklas',
      lastName: 'comes',
      role: 'Betreuer*in',
    },
  ],
});

teamMap.set('DTV', {
  name: 'Dürener TV',
  logo: 'assets/dueren_logo.jpg',
  foto: 'assets/dueren_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Hassler',
      firstName: 'Frederick',
      year: 2007,
      position: 'Z',
    },
    {
      number: 2,
      lastName: 'Faber',
      firstName: 'Matthias',
      year: 2005,
      position: 'Z',
    },
    {
      number: 3,
      lastName: 'Speer',
      firstName: 'Paul',
      year: 2008,
      position: 'Z',
    },
    {
      number: 4,
      lastName: 'Müller',
      firstName: 'Tobias',
      year: 2005,
      position: 'AA',
    },
    {
      number: 5,
      lastName: 'Ulrich',
      firstName: 'Rafic',
      year: 2005,
      position: 'AA',
    },
    {
      number: 6,
      lastName: 'Floß',
      firstName: 'Jonas',
      year: 2008,
      position: 'AA',
    },
    {
      number: 7,
      lastName: 'Middendorf',
      firstName: 'Simon',
      year: 2006,
      position: 'AA',
    },
    {
      number: 8,
      lastName: 'Trataris',
      firstName: 'Alexis',
      year: 2005,
      position: 'AA',
    },
    {
      number: 9,
      lastName: 'Bröcker',
      firstName: 'David',
      year: 2008,
      position: 'AA',
    },
    {
      number: 10,
      lastName: 'Wälde',
      firstName: 'Aaron',
      year: 2005,
      position: 'AA',
    },
    {
      number: 11,
      lastName: 'Becker',
      firstName: 'Tom',
      year: 2005,
      position: 'MB',
    },
    {
      number: 12,
      lastName: 'Quandel',
      firstName: 'Joshua',
      year: 2005,
      position: 'MB',
    },
    {
      number: 13,
      lastName: 'Sultan',
      firstName: 'Hamid',
      year: 2006,
      position: 'MB',
    },
    {
      number: 14,
      lastName: 'Christ',
      firstName: 'Lenn',
      year: 2008,
      position: 'MB',
    },
    {
      number: 15,
      lastName: 'Eckstein',
      firstName: 'Tim',
      year: 2005,
      position: 'L',
    },
  ],
  coaches: [
    {
      firstName: 'André',
      lastName: 'Berger',
      role: 'Trainer*in',
    },
    {
      firstName: 'Wolfgang',
      lastName: 'Obladen',
      role: 'Trainer*in',
    },
    {
      firstName: 'Stefan',
      lastName: 'Maschke',
      role: 'Trainer*in',
    },
  ],
});

teamMap.set('MSV', {
  name: 'Meckenheimer SV',
  logo: 'assets/msv_logo.jpg',
  foto: 'assets/msv_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Bernards',
      firstName: 'Kjell',
      year: 2008,
      position: 'L',
    },
    {
      number: 2,
      lastName: 'Dolpp',
      firstName: 'Jan',
      year: 2008,
      position: 'AA',
    },
    {
      number: 3,
      lastName: 'Flegel',
      firstName: 'Elias',
      year: 2005,
      position: 'AA',
    },
    {
      number: 4,
      lastName: 'Flegel',
      firstName: 'Simon',
      year: 2008,
      position: 'AA',
    },
    {
      number: 5,
      lastName: 'Huthwelker',
      firstName: 'Luis',
      year: 2007,
      position: 'L',
    },
    {
      number: 6,
      lastName: 'Neswabda',
      firstName: 'Felix',
      year: 2007,
      position: 'AA',
    },
    {
      number: 7,
      lastName: 'Quade',
      firstName: 'Max',
      year: 2008,
      position: 'D',
    },
    {
      number: 8,
      lastName: 'Schnurpfeil',
      firstName: 'Johannes',
      year: 2006,
      position: 'MB',
    },
    {
      number: 9,
      lastName: 'Sistig',
      firstName: 'Wolfram',
      year: 2006,
      position: 'MB',
    },
    {
      number: 10,
      lastName: 'Svec',
      firstName: 'Martin',
      year: 2007,
      position: 'MB',
    },
    {
      number: 11,
      lastName: 'Wierzbicki',
      firstName: 'Marco',
      year: 2008,
      position: 'Z',
    },
  ],
  coaches: [
    {
      lastName: 'Rehm',
      firstName: 'Paul',
      role: 'Trainer*in',
    },
  ],
});

teamMap.set('TUB', {
  name: 'TuB Bocholt 1907 e.v.',
  logo: 'assets/tub_logo.jpg',
  foto: 'assets/tub_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Valhbrock',
      firstName: 'Marlon',
      year: 2005,
      position: 'AA',
    },
    {
      number: 2,
      lastName: 'Maaß',
      firstName: 'Alexander',
      year: 2007,
      position: 'Z',
    },
    {
      number: 3,
      lastName: 'Meckelholt',
      firstName: 'Joos',
      year: 2006,
      position: 'AA',
    },
    {
      number: 4,
      lastName: 'Kaya',
      firstName: 'Luka',
      year: 2005,
      position: 'D',
    },
    {
      number: 5,
      lastName: 'Dörpinghaus',
      firstName: 'Ben',
      year: 2007,
      position: 'D',
    },
    {
      number: 6,
      lastName: 'Bandrowski',
      firstName: 'Matthias',
      year: 2006,
      position: 'L',
    },
    {
      number: 7,
      lastName: 'Hüls',
      firstName: 'Jendrik',
      year: 2007,
      position: 'MB',
    },
    {
      number: 8,
      lastName: 'Grotstabel',
      firstName: 'Finn',
      year: 2006,
      position: 'MB',
    },
    {
      number: 9,
      lastName: 'Große-Vehne',
      firstName: 'Jonathan',
      year: 2007,
      position: 'AA',
    },
    {
      number: 10,
      lastName: 'Lehmbrock',
      firstName: 'Hauke',
      year: 2007,
      position: 'AA',
    },
    {
      number: 11,
      lastName: 'Verhasselt',
      firstName: 'Colin',
      year: 2006,
      position: 'MB',
    },
    {
      number: 12,
      lastName: 'Telaar',
      firstName: 'Michel',
      year: 2007,
      position: 'L',
    },
    {
      number: 13,
      lastName: 'Lörcks',
      firstName: 'Jonas',
      year: 2007,
      position: 'MB',
    },
    {
      number: 14,
      lastName: 'Janitzki',
      firstName: 'Nico',
      year: 2007,
      position: 'AA',
    },
  ],
  coaches: [
    {
      lastName: 'Böhme',
      firstName: 'Sven',
      role: 'Trainer*in',
    },
    {
      firstName: 'Jens',
      lastName: 'Dörpinghaus',
      role: 'Betreuer*in',
    },
  ],
});

teamMap.set('TB', {
  name: 'VFL Telstar Bochum',
  logo: 'assets/tb_logo.jpg',
  foto: 'assets/tb_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Bungert',
      firstName: 'Linus',
      year: 2007,
      position: 'AA',
    },
    {
      number: 2,
      lastName: 'Wenzel',
      firstName: 'Erik',
      year: 2006,
      position: 'D',
    },
    {
      number: 3,
      lastName: 'Witteler',
      firstName: 'Jakob',
      year: 2006,
      position: 'MB',
    },
    {
      number: 4,
      lastName: 'Becker',
      firstName: 'Justus',
      year: 2005,
      position: 'Z',
    },
    {
      number: 5,
      lastName: 'Hüttemann',
      firstName: 'Vince',
      year: 2006,
      position: 'AA',
    },
    {
      number: 6,
      lastName: 'Grauberger',
      firstName: 'Kevin',
      year: 2006,
      position: 'L',
    },
    {
      number: 7,
      lastName: 'Paho',
      firstName: 'Marino',
      year: 2007,
      position: 'MB',
    },
    {
      number: 8,
      lastName: 'Tassikov',
      firstName: 'Dennis',
      year: 2007,
      position: 'Z',
    },
    {
      number: 9,
      lastName: 'Kuksin',
      firstName: 'Andreas',
      year: 2007,
      position: 'AA',
    },
    {
      number: 10,
      lastName: 'Merten',
      firstName: 'Daniel',
      year: 2005,
      position: 'D',
    },
    {
      number: 11,
      lastName: 'Schnetz',
      firstName: 'Carl',
      year: 2007,
      position: 'L',
    },
    {
      number: 12,
      lastName: 'Minzlaff',
      firstName: 'Eric',
      year: 2008,
      position: 'AA',
    },
    {
      number: 13,
      lastName: 'Alharfoosh',
      firstName: 'Talal',
      year: 2008,
      position: 'Z',
    },
    {
      number: 14,
      lastName: 'Djedipour',
      firstName: 'Arian',
      year: 2007,
      position: 'MB',
    },
    {
      number: 15,
      lastName: 'Smo',
      firstName: 'Zana',
      year: 2008,
      position: 'AA',
    },
  ],
  coaches: [
    {
      firstName: 'Matthias',
      lastName: 'Goldenbogen',
      role: 'Trainer*in',
    },
    {
      firstName: 'Eren',
      lastName: 'Gelincik',
      role: 'Trainer*in',
    },
    {
      firstName: 'Marc',
      lastName: 'Rößler',
      role: 'Betreuer*in',
    },
  ],
});

teamMap.set('DJKRN', {
  name: 'DJK Rheinkraft Neuss',
  logo: 'assets/djkrn_logo.jpg',
  foto: 'assets/djkrn_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Amrin',
      firstName: 'Alan',
      year: 0,
      position: 'Z',
    },
    {
      number: 2,
      lastName: 'Sumpf',
      firstName: 'Philipp',
      year: 0,
      position: 'AA',
    },
    {
      number: 3,
      lastName: 'Demirel',
      firstName: 'Engin',
      year: 0,
      position: 'MB',
    },
    {
      number: 4,
      lastName: 'Mikulasch',
      firstName: 'Carlo',
      year: 0,
      position: 'MB',
    },
    {
      number: 5,
      lastName: 'Muckel',
      firstName: 'Joon',
      year: 0,
      position: 'MB',
    },
    {
      number: 6,
      lastName: 'Wilkesmann',
      firstName: 'Bennet',
      year: 0,
      position: 'AA',
    },
    {
      number: 7,
      lastName: 'Vogt',
      firstName: 'Matteo',
      year: 0,
      position: 'AA',
    },
    {
      number: 8,
      lastName: 'Possberg',
      firstName: 'Lenn',
      year: 0,
      position: 'D',
    },
    {
      number: 9,
      lastName: 'Zagorje',
      firstName: 'Joel',
      year: 0,
      position: 'L',
    },
    {
      number: 10,
      lastName: 'Wilmesmeyer',
      firstName: 'Laurenz',
      year: 0,
      position: 'L',
    },
    {
      number: 11,
      lastName: 'Tampere',
      firstName: 'Nikolas',
      year: 0,
      position: 'D',
    },
  ],
  coaches: [
    {
      firstName: 'Nikolaj',
      lastName: 'Konarew',
      role: 'Trainer*in',
    },
    {
      firstName: 'Artjom',
      lastName: 'Schalaew',
      role: 'Betreuer*in',
    },
  ],
});

teamMap.set('MSC', {
  name: 'Moerser SC',
  logo: 'assets/msc_logo.jpg',
  foto: 'assets/msc_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Bartsch',
      firstName: 'Luis Fabian',
      year: 2005,
      position: 'MB',
    },
    {
      number: 2,
      lastName: 'Bemoth',
      firstName: 'Timo',
      year: 2008,
      position: 'AA',
    },
    {
      number: 3,
      lastName: 'Bertea',
      firstName: 'Fabio Leandro',
      year: 2005,
      position: 'Z',
    },
    {
      number: 4,
      lastName: 'Bertea',
      firstName: 'Valentino Alessio',
      year: 2008,
      position: 'Z',
    },
    {
      number: 5,
      lastName: 'Kivule',
      firstName: 'Luc',
      year: 2006,
      position: 'MB',
    },
    {
      number: 6,
      lastName: 'Kugel',
      firstName: 'Quentin',
      year: 2006,
      position: 'L',
    },
    {
      number: 7,
      lastName: 'Pukownik',
      firstName: 'Jona',
      year: 2008,
      position: 'D',
    },
    {
      number: 8,
      lastName: 'Schumann',
      firstName: 'Joshua',
      year: 2007,
      position: 'AA',
    },
    {
      number: 9,
      lastName: 'Shchokin',
      firstName: 'Dmytro',
      year: 2006,
      position: 'D',
    },
    {
      number: 10,
      lastName: 'Tanneberger',
      firstName: 'Tobias',
      year: 2008,
      position: 'MB',
    },
    {
      number: 11,
      lastName: 'Tran',
      firstName: 'Jason',
      year: 2006,
      position: 'L',
    },
    {
      number: 12,
      lastName: 'Wachtel',
      firstName: 'Oliver Maxim',
      year: 2007,
      position: 'U',
    },
  ],
  coaches: [
    {
      lastName: 'Rieskamp',
      firstName: 'Hendrik',
      role: 'Trainer*in',
    },
    {
      lastName: 'Pukownik',
      firstName: 'Markus',
      role: 'Betreuer*in',
    },
  ],
});

teamMap.set('TPSVB', {
  name: 'Telekom Post SV Bielefeld',
  logo: 'assets/tpsvb_logo.jpg',
  foto: 'assets/tpsvb_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Berkenkamp',
      firstName: 'Eric',
      year: 2005,
      position: 'D',
    },
    {
      number: 2,
      lastName: 'Fot',
      firstName: 'Daniel',
      year: 2006,
      position: 'AA/L',
    },
    {
      number: 3,
      lastName: 'Hausmann',
      firstName: 'Carl',
      year: 2006,
      position: 'D',
    },
    {
      number: 4,
      lastName: 'Jandrey',
      firstName: 'Fabian',
      year: 2006,
      position: 'AA',
    },
    {
      number: 5,
      lastName: 'Janzen',
      firstName: 'Finn',
      year: 2007,
      position: 'AA',
    },
    {
      number: 6,
      lastName: 'Kartal',
      firstName: 'Leon',
      year: 2006,
      position: 'MB',
    },
    {
      number: 7,
      lastName: 'Kentzler',
      firstName: 'Henry',
      year: 2005,
      position: 'Z',
    },
    {
      number: 8,
      lastName: 'Kopera',
      firstName: 'Paul',
      year: 2007,
      position: 'D',
    },
    {
      number: 9,
      lastName: 'Mersch',
      firstName: 'Jakob',
      year: 2006,
      position: 'Z',
    },
    {
      number: 10,
      lastName: 'Rezayee',
      firstName: 'Ferdin',
      year: 2006,
      position: 'AA/MB',
    },
    {
      number: 11,
      lastName: 'Schwarz',
      firstName: 'Lasse',
      year: 2005,
      position: 'AA',
    },
    {
      number: 12,
      lastName: 'Strate',
      firstName: 'Tom',
      year: 2005,
      position: 'MB',
    },
    {
      number: 13,
      lastName: 'Suden',
      firstName: 'Jarik',
      year: 2005,
      position: 'L',
    },
    {
      number: 14,
      lastName: 'Unruh',
      firstName: 'Fabio',
      year: 2006,
      position: 'MB',
    },
  ],
  coaches: [
    {
      lastName: 'Schade',
      firstName: 'Anne-Kathrin',
      role: 'Trainer*in',
    },
    {
      lastName: 'Grau',
      firstName: 'Andreas',
      role: 'Trainer*in',
    },
    {
      lastName: 'Keilbart',
      firstName: 'Tom',
      role: 'Trainer*in',
    },
  ],
});

teamMap.set('VRP', {
  name: 'Volleyball Regionalkader Paderborn',
  logo: 'assets/vrp_logo.jpg',
  foto: 'assets/vrp_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Buttgereit',
      firstName: 'Johannes',
      year: 2006,
      position: 'L',
    },
    {
      number: 2,
      lastName: 'Hasse',
      firstName: 'Fabio',
      year: 2005,
      position: 'Z',
    },
    {
      number: 3,
      lastName: 'Kroll',
      firstName: 'René',
      year: 2006,
      position: 'AA/D',
    },
    {
      number: 4,
      lastName: 'Bialas',
      firstName: 'Oskar',
      year: 2006,
      position: 'L',
    },
    {
      number: 5,
      lastName: 'Kubi',
      firstName: 'Lukas',
      year: 2007,
      position: 'MB',
    },
    {
      number: 6,
      lastName: 'Kuzhel',
      firstName: 'Darii',
      year: 2008,
      position: 'AA',
    },
    {
      number: 7,
      lastName: 'Grabe',
      firstName: 'Till',
      year: 2005,
      position: 'D',
    },
    {
      number: 8,
      lastName: 'Hinz',
      firstName: 'Justus',
      year: 2005,
      position: 'AA',
    },
    {
      number: 9,
      lastName: 'Fomin',
      firstName: 'Maksym',
      year: 2006,
      position: 'MB',
    },
    {
      number: 10,
      lastName: 'Filiniuk',
      firstName: 'Pavlo',
      year: 2005,
      position: 'AA',
    },
    {
      number: 11,
      lastName: 'Sprehe',
      firstName: 'Jonas',
      year: 2006,
      position: 'MB',
    },
    {
      number: 12,
      lastName: 'Hensen',
      firstName: 'Justus',
      year: 2006,
      position: 'AA',
    },
    {
      number: 13,
      lastName: 'Kamrath',
      firstName: 'Noah',
      year: 2006,
      position: 'MB',
    },
    {
      number: 14,
      lastName: 'Warmus',
      firstName: 'Luca',
      year: 2006,
      position: 'Z',
    },
  ],
  coaches: [
    { firstName: 'Niklas', lastName: 'Hinz', role: 'Trainer*in' },
    { firstName: 'Eduard', lastName: 'Kubi', role: 'Betreuer*in' },
  ],
});

teamMap.set('SGA', {
  name: 'SG Aachen',
  logo: 'assets/sga_logo.jpg',
  foto: 'assets/sga_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Arndt',
      firstName: 'Titus',
      year: 2007,
      position: 'AA',
    },
    {
      number: 2,
      lastName: 'Bund',
      firstName: 'Philipp',
      year: 2006,
      position: 'AA',
    },
    {
      number: 3,
      lastName: 'Fava Welter Ribeiro',
      firstName: 'Tomás',
      year: 2006,
      position: 'D',
    },
    {
      number: 4,
      lastName: 'Füchsel',
      firstName: 'Joe',
      year: 2006,
      position: 'Z',
    },
    {
      number: 5,
      lastName: 'Gyllensvärd',
      firstName: 'Rasmus',
      year: 2007,
      position: 'MB',
    },
    {
      number: 6,
      lastName: 'Hannes',
      firstName: 'Fiete',
      year: 2005,
      position: 'MB',
    },
    {
      number: 7,
      lastName: 'Heigold',
      firstName: 'Christoph',
      year: 2007,
      position: 'Z',
    },
    {
      number: 8,
      lastName: 'Klostermann',
      firstName: 'Justus',
      year: 2007,
      position: 'MB',
    },
    {
      number: 9,
      lastName: 'Leuchter',
      firstName: 'David',
      year: 2007,
      position: 'L',
    },
    {
      number: 10,
      lastName: 'Meisel',
      firstName: 'Jenrik',
      year: 2005,
      position: 'Z',
    },
    {
      number: 11,
      lastName: 'Steffan',
      firstName: 'Oskar',
      year: 2006,
      position: 'D',
    },
    {
      number: 12,
      lastName: 'Stüve',
      firstName: 'Ben',
      year: 2005,
      position: 'AA',
    },
    {
      number: 13,
      lastName: 'Tonnesen',
      firstName: 'Henrik',
      year: 2005,
      position: 'AA',
    },
    {
      number: 14,
      lastName: 'Ward',
      firstName: 'Max',
      year: 2005,
      position: 'MB',
    },
  ],
  coaches: [
    {
      firstName: 'Axel',
      lastName: 'Leuchter',
      role: 'Trainer*in',
    },
    {
      firstName: 'Thorsten',
      lastName: 'Tonnesen',
      role: 'Betreuer*in',
    },
  ],
});

teamMap.set('TVH', {
  name: 'TV Hörde',
  logo: 'assets/tvh_logo.jpg',
  foto: 'assets/tvh_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Barthel',
      firstName: 'Jens',
      year: 2005,
      position: 'MB',
    },
    {
      number: 2,
      lastName: 'Friesen',
      firstName: 'Nikita',
      year: 2007,
      position: 'L',
    },
    {
      number: 3,
      lastName: 'Hashemi',
      firstName: 'Arastou',
      year: 2008,
      position: 'Z',
    },
    {
      number: 4,
      lastName: 'Horelov',
      firstName: 'Maksim',
      year: 2006,
      position: 'AA',
    },
    {
      number: 5,
      lastName: 'Kinze',
      firstName: 'Lars',
      year: 2006,
      position: 'MB',
    },
    {
      number: 7,
      lastName: 'Klein',
      firstName: 'Tim',
      year: 2006,
      position: 'MB',
    },
    {
      number: 8,
      lastName: 'Kukoljac',
      firstName: 'Andrej',
      year: 2006,
      position: 'MB',
    },
    {
      number: 9,
      lastName: 'Köster',
      firstName: 'Niklas',
      year: 2006,
      position: 'MB',
    },
    {
      number: 10,
      lastName: 'Ostmann',
      firstName: 'Jacob',
      year: 2005,
      position: 'L',
    },
    {
      number: 11,
      lastName: 'Ploke',
      firstName: 'Philipp',
      year: 2007,
      position: 'AA',
    },
    {
      number: 12,
      lastName: 'Rodegro',
      firstName: 'Linus Valentin',
      year: 2005,
      position: 'D',
    },
    {
      number: 13,
      lastName: 'Slacanin',
      firstName: 'Tyreese',
      year: 2005,
      position: 'AA',
    },
    {
      number: 14,
      lastName: 'Steiner',
      firstName: 'Maximilian',
      year: 2005,
      position: 'Z',
    },
  ],
  coaches: [
    { firstName: 'Tom', lastName: 'Barthel', role: 'Trainer*in' },
    { firstName: 'Phil', lastName: 'Schulenburg', role: 'Trainer*in' },
    { firstName: 'Jan', lastName: 'Pieper', role: 'Trainer*in' },
  ],
});

teamMap.set('RTV', {
  name: 'Rumelner TV',
  logo: 'assets/rtv_logo.jpg',
  foto: 'assets/rtv_foto.jpg',
  players: [
    {
      number: 6,
      lastName: 'Bungert',
      firstName: 'Jonathan',
      year: 2008,
      position: 'AA',
    },
    {
      number: 3,
      lastName: 'Dalquen',
      firstName: 'Niclas',
      year: 2008,
      position: 'D',
    },
    {
      number: 17,
      lastName: 'Drammeh',
      firstName: 'Bangally',
      year: 2005,
      position: 'MB',
    },
    {
      number: 14,
      lastName: 'Fischer',
      firstName: 'Florian',
      year: 2008,
      position: 'MB',
    },
    {
      number: 8,
      lastName: 'Hikel',
      firstName: 'Julian',
      year: 2006,
      position: 'AA',
    },
    {
      number: 2,
      lastName: 'Kaidalov',
      firstName: 'Anton',
      year: 2005,
      position: 'AA',
    },
    {
      number: 12,
      lastName: 'Kinder',
      firstName: 'Tobias',
      year: 2006,
      position: 'U',
    },
    {
      number: 23,
      lastName: 'Kindermann',
      firstName: 'Marten',
      year: 2006,
      position: 'MB',
    },
    {
      number: 26,
      lastName: 'Ly',
      firstName: 'Eric',
      year: 2007,
      position: 'Z',
    },
    {
      number: 22,
      lastName: 'Mogendorf',
      firstName: 'Mats',
      year: 2006,
      position: 'MB',
    },
    {
      number: 5,
      lastName: 'Reckeweg',
      firstName: 'Julius',
      year: 2006,
      position: 'U',
    },
    {
      number: 9,
      lastName: 'Thiedmann',
      firstName: 'Kai',
      year: 2007,
      position: 'L',
    },
    {
      number: 26,
      lastName: 'Weissenbach',
      firstName: 'Levi',
      year: 2007,
      position: 'AA',
    },
    {
      number: 4,
      lastName: 'Wenke',
      firstName: 'Kylian',
      year: 2008,
      position: 'Z',
    },
  ],
  coaches: [
    { firstName: 'Marc', lastName: 'Kindermann', role: 'Trainer*in' },
    { firstName: 'Tom', lastName: 'Hikel', role: 'Betreuer*in' },
  ],
});

teamMap.set('TSC', {
  name: 'TSC Gievenbeck',
  logo: 'assets/tsc_logo.jpg',
  foto: 'assets/tsc_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Lembeck',
      firstName: 'Oskar',
      year: 2006,
      position: 'Z',
    },
    {
      number: 2,
      lastName: 'Steller',
      firstName: 'Luca',
      year: 2007,
      position: 'Z',
    },
    {
      number: 3,
      lastName: 'Wunnicke',
      firstName: 'Cedric',
      year: 2007,
      position: 'L',
    },
    {
      number: 4,
      lastName: 'Jona',
      firstName: 'Lyn',
      year: 2006,
      position: 'D',
    },
    {
      number: 5,
      lastName: 'Hülsbusch',
      firstName: 'Noah',
      year: 2007,
      position: 'D',
    },
    {
      number: 6,
      lastName: 'Ruhe',
      firstName: 'Robin',
      year: 2006,
      position: 'MB',
    },
    {
      number: 7,
      lastName: 'Herrmann',
      firstName: 'Onno',
      year: 2007,
      position: 'MB',
    },
    {
      number: 8,
      lastName: 'Regenbogen',
      firstName: 'Ole',
      year: 2008,
      position: 'MB',
    },
    {
      number: 9,
      lastName: 'Busse',
      firstName: 'Nicolas',
      year: 2008,
      position: 'MB',
    },
    {
      number: 10,
      lastName: 'Peters',
      firstName: 'Marten',
      year: 2007,
      position: 'AA',
    },
    {
      number: 11,
      lastName: 'Bevers',
      firstName: 'Elias',
      year: 2007,
      position: 'AA',
    },
    {
      number: 12,
      lastName: 'Haarstick',
      firstName: 'Leo',
      year: 2006,
      position: 'AA',
    },
    {
      number: 13,
      lastName: 'Popinski',
      firstName: 'Kamil',
      year: 2008,
      position: 'AA',
    },
  ],
  coaches: [
    { firstName: 'Friedrich', lastName: 'Nagel', role: 'Trainer*in' },
    { firstName: 'Dominik', lastName: 'Rutke', role: 'Betreuer*in' },
  ],
});

teamMap.set('WVV', {
  name: 'WVV Auswahl',
  logo: 'assets/wvv_logo.jpg',
  foto: 'assets/wvv_foto.jpg',
  players: [
    {
      number: 0,
      lastName: 'Calignano',
      firstName: 'Filippo',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Rdesinski',
      firstName: 'Michal',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Epp',
      firstName: 'Ben',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Strubel',
      firstName: 'Artem',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Nkumu',
      firstName: 'Aggee',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Kentzler',
      firstName: 'Levi',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Paltian',
      firstName: 'David',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Gieseking',
      firstName: 'Jakob',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Herbe',
      firstName: 'Mats',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Kern',
      firstName: 'Moritz',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Goos',
      firstName: 'Benjamin',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Mücke',
      firstName: 'Pepe',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Küppers',
      firstName: 'Benjamin',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Laufenberg',
      firstName: 'Julian',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Kochs',
      firstName: 'Milton',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Kelp',
      firstName: 'Vincent',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Treuling',
      firstName: 'Nilo',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Jost',
      firstName: 'Felix',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Zierdt',
      firstName: 'Jakob',
      year: 2009,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Bucholz',
      firstName: 'Lutz',
      year: 2010,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Kuckuck',
      firstName: 'Lino',
      year: 2010,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Vinke',
      firstName: 'Tjark',
      year: 2010,
      position: 'Unbekannt',
    },
    {
      number: 0,
      lastName: 'Plotz',
      firstName: 'Jonne',
      year: 2010,
      position: 'Unbekannt',
    },
  ],
  coaches: [
    { firstName: 'Oliver', lastName: 'Gies', role: 'Trainer*in' },
    { firstName: 'Louis', lastName: 'Wieczorek', role: 'Trainer*in' },
    { firstName: 'Carolin', lastName: 'Hellmann', role: 'Trainer*in' },
    { firstName: 'Carolin', lastName: 'Wynands', role: 'Physotherapeut*in' },
  ],
});

teamMap.set('FCJ', {
  name: 'FCJ Köln',
  logo: 'assets/fcj_logo.jpg',
  foto: 'assets/fcj_foto.jpg',
  players: [
    {
      number: 1,
      lastName: 'Meier',
      firstName: 'Jan Ole',
      year: 2005,
      position: 'Z',
    },
    {
      number: 2,
      lastName: 'Weidenfeld',
      firstName: 'Piet',
      year: 2007,
      position: 'Z',
    },
    {
      number: 3,
      lastName: 'Puck',
      firstName: 'Christian',
      year: 2006,
      position: 'D',
    },
    {
      number: 4,
      lastName: 'Tein',
      firstName: 'Philip',
      year: 2006,
      position: 'AA',
    },
    {
      number: 5,
      lastName: 'Schipp',
      firstName: 'Moritz',
      year: 2005,
      position: 'AA',
    },
    {
      number: 6,
      lastName: 'Wallau',
      firstName: 'Robin',
      year: 2005,
      position: 'AA',
    },
    {
      number: 7,
      lastName: 'Lilkendey',
      firstName: 'Lennox',
      year: 2006,
      position: 'AA',
    },
    {
      number: 8,
      lastName: 'Buckert',
      firstName: 'Linus',
      year: 2006,
      position: 'AA',
    },
    {
      number: 9,
      lastName: 'Moammer',
      firstName: 'Arian',
      year: 2005,
      position: 'L',
    },
    {
      number: 10,
      lastName: 'Bastheim',
      firstName: 'Ferdinand',
      year: 2008,
      position: 'MB',
    },
    {
      number: 11,
      lastName: 'Stähle',
      firstName: 'Felix',
      year: 2008,
      position: 'MB',
    },
    {
      number: 12,
      lastName: 'Schink',
      firstName: 'Philipp',
      year: 2006,
      position: 'MB',
    },
    {
      number: 13,
      lastName: 'Niels',
      firstName: 'Mika',
      year: 2006,
      position: 'MB',
    },
    {
      number: 14,
      lastName: 'Haag',
      firstName: 'Christian',
      year: 2005,
      position: 'MB',
    },
    {
      number: 15,
      lastName: 'Roscher',
      firstName: 'Simon',
      year: 2006,
      position: 'U',
    },
    {
      number: 16,
      lastName: 'Chen',
      firstName: 'Leonard',
      year: 2006,
      position: 'Z',
    },
    {
      number: 17,
      lastName: 'Podlich',
      firstName: 'Matteo',
      year: 2006,
      position: 'L',
    },
    {
      number: 18,
      lastName: 'Iyiköy',
      firstName: 'Batuhan',
      year: 2006,
      position: 'L',
    },
  ],
  coaches: [
    { firstName: 'Kevin', lastName: 'Bradtke', role: 'Trainer*in' },
    { firstName: 'Martin', lastName: 'Emmerich', role: 'Betreuer*in' },
  ],
});
