import { Team } from './teams.component';

export const VVHE: Team = {
  name: 'Volleyball Verein Humann Essen',
  logo: '/assets/vvhe_logo.jpg',
  players: [
    {
      number: 1,
      firstName: 'Jonas',
      lastName: 'Espelage',
      position: 'MB',
      year: 2005,
    },
    {
      number: 2,
      firstName: 'Henry',
      lastName: 'Gerding',
      position: 'AA',
      year: 2006,
    },
    {
      number: 3,
      firstName: 'Luca',
      lastName: 'Grünheit',
      position: 'L',
      year: 2005,
    },
    {
      number: 4,
      firstName: 'Fynn',
      lastName: 'Heymer',
      position: 'AA/L',
      year: 2005,
    },
    {
      number: 5,
      lastName: 'Ignaczak',
      firstName: 'Mika',
      year: 2006,
      position: 'Z',
    },
    {
      number: 6,
      lastName: 'Juditzki',
      firstName: 'Jonah',
      year: 2005,
      position: 'Z',
    },
    {
      number: 7,
      lastName: 'Kott',
      firstName: 'Niklas',
      year: 2005,
      position: 'MB',
    },
    {
      number: 8,
      lastName: 'Köhnen',
      firstName: 'Jakob',
      year: 2005,
      position: 'AA/L',
    },
    {
      number: 9,
      lastName: 'Marijanovic',
      firstName: 'Dejan',
      year: 2006,
      position: 'D',
    },
    {
      number: 10,
      lastName: 'Neuhaus',
      firstName: 'Jakob',
      year: 2005,
      position: 'AA',
    },
    {
      number: 11,
      lastName: 'Prions',
      firstName: 'Moritz',
      year: 2005,
      position: 'D',
    },
    {
      number: 12,
      lastName: 'Strecker',
      firstName: 'Leif',
      year: 2005,
      position: 'MB',
    },
    {
      number: 13,
      lastName: 'Strecker',
      firstName: 'Yul',
      year: 2007,
      position: 'AA/L',
    },
    {
      number: 14,
      lastName: 'Thomzik',
      firstName: 'Piet',
      year: 2005,
      position: 'MB',
    },
    {
      number: 15,
      lastName: 'Müller',
      firstName: 'Milan',
      year: 2005,
      position: 'AA',
    },
  ],
  coaches: [
    {
      lastName: 'Wojtczak',
      firstName: 'Thomas',
      role: 'Trainer/in',
    },
    {
      lastName: 'Mrozek',
      firstName: 'Linus',
      role: 'Betreuer/in',
    },
    {
      firstName: 'Konstantin',
      lastName: 'Brandt',
      role: 'Betreuer/in',
    },
    {
      firstName: 'Till',
      lastName: 'Köhnen',
      role: 'Betreuer/in',
    },
    {
      firstName: 'Lukas',
      lastName: 'Prions',
      role: 'Betreuer/in',
    },
  ],
};

export const RSV: Team = {
  name: 'Rhein-Sieg Volleys',
  logo: 'assets/rsv_logo.png',
  players: [
    {
      firstName: 'Moritz',
      lastName: 'Knipp',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Valentin',
      lastName: 'Mickus',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Julian',
      lastName: 'Sekul',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Yann',
      lastName: 'Pierre',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Valentin',
      lastName: 'Drühl',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Ben',
      lastName: 'Vohwinkel',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Luke',
      lastName: 'Engelke',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Denys',
      lastName: 'Kurylo',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Elias',
      lastName: 'Stommel',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Fynn',
      lastName: 'Bäumer',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Mohammad Soltanzadeh Salahdar',
      lastName: 'Seyed',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Mathias',
      lastName: 'Klein-Heßling',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Till',
      lastName: 'Spies',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Marko',
      lastName: 'Rakovic',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Justus',
      lastName: 'von Alvensleben',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Bjarne',
      lastName: 'Teiwes',
      number: 0,
      year: 0,
      position: 'unknown',
    },
    {
      firstName: 'Arin Qadir',
      lastName: '',
      number: 0,
      year: 0,
      position: 'unknown',
    },
  ],
  coaches: [
    {
      firstName: 'Max',
      lastName: 'Hopf',
      role: 'Trainer/in',
    },
    {
      firstName: 'Jan-Niklas',
      lastName: 'comes',
      role: 'Betreuer/in',
    },
  ],
};
